
package Executed;

import Controller.OrderManager;
import Controller.ShopManagement;
import Model.Order;
import View.Menu;

public class Main extends Menu{
    OrderManager or = new OrderManager();
    ShopManagement sm = new ShopManagement();
    
    public Main(){
        super("\n-*-*-*-*-*Fruit Management*-*-*-*-*-", 
             new String[] {"Auto Generated Fruit","Create Fruit.", "View orders", "Shopping (for buyer)",
                    "Exit!"});
    }
    
    public static void main(String[] args) {
        Main hi = new Main();
        hi.run();
        
    }

    @Override
    public void execute(int choice) {
        switch (choice) {
            case 1:
                sm.autoGeneratedFruit();        //Khởi tạo vật phầm (auto)
                System.out.println("________Done!!________");
                break;
            case 2:
                sm.addFruit();              ///pr.addFruit();
                break;
            case 3:
                or.showAllOrder();      //in all order
                break;
            case 4:
                Order customerNew = sm.getChoiceFruit();
                customerNew = sm.printAllProductWillBuy(customerNew);
                or.Ordering(customerNew);       //lưu trữ
                break;
            case 5:
                System.out.println("Program closing!!!");
                break;
            default:
                System.out.println("We don't had that option!");
                break;
        }
    }
}
